### PR TITLE
Update readthedocs.yml

### PR DESCRIPTION
**Pull request by ebs111222**
please add the option to download the pdf format.
thanks

### CODE REVIEW

**Review by ebs111222 — COMMENTED** [review]
please add 
pdf support

**Comment by ebs111222** [comment]
> We think it's important that the users always go to the latest version which is available as HTML only.

I see, 
Ok I tried to fork it and built it using readthedocs but I get the result in germen, any idea how I can get it in English?
Thanks

**Comment by FlyingToto** [comment]
QQ: what about printing it from the browser then you can print it to a pdf isn't it?

**Comment by ebs111222** [comment]
> @ebs111222 , QQ: what about printing it from the browser then you can print it to a pdf isn't it?

hi,
yes i can but if you create a pdf in readthedocs it creates it like abook, with page structure and all,
i want to build it myself so i can sit and read it all.
i cannot build it in english for some reason, can you please help?
thanks

**Pull request closed without merging**
