### PR TITLE
Update module.rst

### PR DESCRIPTION
**Pull request by guydavies**
add missing space
minor changes to highlight the ability of Xdrip to alarm in silent mode

### CODE REVIEW

**Comment by xJoe** [comment]
Thanks for your proposal. Changes in language specific versions must be made in Crowdin. Could you do it there?
See https://androidaps.readthedocs.io/en/latest/CROWDIN/fr/translations.html

**Comment by guydavies** [comment]
Ok. Thanks Joe. I'll take a look

Rgds

Guy

**Comment by guydavies** [comment]
Hmm. I'm not sure you'll accept me as a proofreader since I have no
translation qualifications. But my suggestions are editorial rather than
translating new sections of text.

Also French is not my mother tongue although I'm a French citizen living
here for over 10 years now

**Comment by xJoe** [comment]
You can work as translator and someone else will do proofreading. That‘s standard procedure.

**Comment by guydavies** [comment]
Yeah. Philloul asked me to proofread their translations. He?'s done all of
the translations.

**Pull request closed without merging**
