### PR TITLE
Impact of settings table added

### PR DESCRIPTION
**Pull request by dexdan**
Added a draft table, for comment, of impact of various AAPS settings. Will send a link round FB for comment.

### CODE REVIEW

**Comment by typ1-brods** [comment]
This is great work, @dexdan! Thanks for it. Please review my comment, then I'll merge

**Comment by dexdan** [comment]
> This is great work, @dexdan! Thanks for it. Please review my comment, then I'll merge

Many thanks @typ1-brods.... very sorry for being slow but I can't seem to see you comments on github? Where can I see them? Thanks & sorry

**Comment by typ1-brods** [comment]
https://github.com/openaps/AndroidAPSdocs/pull/363/files

**Comment by dexdan** [comment]
> https://github.com/openaps/AndroidAPSdocs/pull/363/files

Very sorry but I can't see any comments on there, even when 'view comments' is ticked in the menu from the three dots on the top right?.....

Can you paste your comment into this conversation chain and I'll very gladly amend as sensible....

Thanks & sorry

**Comment by typ1-brods** [comment]
Oh sure. The only comment was: Please add mg/dl per U as it is another possibly unit for ISF

**Comment by dexdan** [comment]
> Oh sure. The only comment was: Please add mg/dl per U as it is another possibly unit for ISF

Great many thanks. Have amended - thanks in advance for the merge. --Dan

**Pull request merged**
