### PR TITLE
Update Screenshots.md

### PR DESCRIPTION
**Pull request by roppenheimer**
Starting to work on the Screenshots page

### CODE REVIEW

**Comment by AdrianLxM** [comment]
Hi, really appreciate this. It would be good though to add the screenshots to the PR instead of linking another repo.

**Comment by roppenheimer** [comment]
Yes, I know, but I’ve never used GitHub before and I was struggling with how it works. Not sure how to do that.

**Comment by danamlewis** [comment]
@roppenheimer I wrote something last year in the OpenAPS docs to help with multiple images - it may need updating, but hopefully it's enough to help you get started: https://openaps.readthedocs.io/en/latest/docs/Resources/my-first-pr.html#advanced-tips-for-adding-multiple-images-to-documentation (generally - steps are to upload all the images to the AndroidAPS docs repo, and then link to them from whatever page you're wanting to add them to). Just found a PM from you in the requests folder, so I'll respond there & let me know if I can help.

**Comment by AdrianLxM** [comment]
Closing this PR, it is included in https://github.com/openaps/AndroidAPSdocs/pull/12

**Pull request closed without merging**
