### PR TITLE
create howto for Huawei phones

### PR DESCRIPTION
**Pull request by gregorybel**

### CODE REVIEW

**Comment by MilosKozak** [comment]
link it from rst file

**Comment by typ1-brods** [comment]
You can find the index.rst under docs/EN/index.rst Just add your new page for navigation

**Comment by gregorybel** [comment]
done, sorry having forgotten it but thanks catching this!

**Comment by xJoe** [comment]
@gregorybel could you provide screenshots of Huawei settings? Would make it easier to follow. Thanks.

**Pull request merged**
