### PR TITLE
Fix various build warnings

### PR DESCRIPTION
**Pull request by Andries-Smit**
The total repo has over 11.000 warning during build. This is unhealthy practice too keep them in. This will prevent us from upgrading in the future. Some the fixes are `code` cosmetic and some are broken links or incorrect use of md and rst format.

The first target is to get all warning from the source language English. And there after in priority of % translated languages. 

This PR fixes over 300 warning, fixing various issues:
- indents with 3 spaces, => 2 spaces
- horizontal line is not allowed as first item after a heading => removed line
- some .rst italic was written with underscores (as in .md) but they are links in rst => replace _ with *
- some * (italic) are not where not closed => add closing *
- some list contained a newline => removed newline
- Some rst headers where to short => made the longer
- rst lists should end with a empty line => added extra line
- some alt text was wrong indented, causes not to match with the image => added spaces

The PR in independent of #969

### CODE REVIEW

**Comment by teleriddler** [comment]
Thanks for running through these Andries-Smit.  FYI, I used a document to RST converter on the initial conversion of the document and cleaned it up.  Thought I got all of the conversion mistakes but looks like you found 2 I missed.

Question:  Are you doing this scan programmatically?  If so, can I ask how and what script you are using?  If not then thank you for taking the time to manually look through each document.  I know how consuming it can be.

TR

**Comment by xJoe** [comment]
I don't think links without file extension work for md files.
https://androidaps.readthedocs.io/en/latest/EN/make-a-PR.html#links

**Comment by Andries-Smit** [comment]
@teleriddler When building the docs locally you can check all warning. Also there are some good extension for IDEs (Not so easy to setup though) https://marketplace.visualstudio.com/items?itemName=lextudio.restructuredtext
I am working on #969 this will allow is to run builds in the GitHub Actions to validate PR for build warning.

**Comment by Andries-Smit** [comment]
@xJoe  It seems to work... https://androidapsdocs.readthedocs.io/en/fix-build-errors-en/
Though I am not completely happy with removing them. As it seems that link within the whole documentation is a mess. And we might want to review the in an other round.

**Comment by Andries-Smit** [comment]
@xJoe I reverted the extension commit. Please merge at will.

**Comment by Andries-Smit** [comment]
@xJoe Could please you merge this one too?

**Comment by xJoe** [comment]
Sorry. Was on bottom of the list and overseen.

**Pull request merged**
