### PR TITLE
Add spellchecker for English files

### PR DESCRIPTION
**Pull request by anbraten**
Noticed quite some typos and thought it might be nice to have a spellchecker for English. 

Not sure, but I assume all translations can be spellchecked in crowdin.

### CODE REVIEW

**Comment by peterleimbach** [comment]
@anbraten This will setup a new action which is fired for every merge on the master and checks the spelling for the english version but ignores - which is right - the CROWDIN directory.

**Comment by peterleimbach** [comment]
@anbraten Sorry. The comment above was a question as I am not totally sure what you propose. Can you please comment?

**Comment by anbraten** [comment]
@peterleimbach The idea was to have an spellchecker for the english content to prevent typos and similar spelling mistakes.

**Comment by peterleimbach** [comment]
@anbraten Thank you.

**Pull request merged**
