### PR TITLE
Remove unused images

### PR DESCRIPTION
**Pull request by anbraten**
Removed unused images from docs so translators do not translate / update images that aren't used at all. It will also speed up the crowdin sync drastically if we don't upload those files.

### CODE REVIEW

**Comment by anbraten** [comment]
As it includes #2011 we need to fix that one first.

**Comment by peterleimbach** [comment]
@anbraten Thank you. But why not just delete them?

**Comment by anbraten** [comment]
@peterleimbach We can also delete them.

**Comment by psonnera** [comment]
@anbraten can you check the list is still up to date? This would be a good idea to get rid of them indeed,

**Comment by anbraten** [comment]
@psonnera Sure, I will check the list again and update tonight if necessary

**Comment by anbraten** [comment]
I've checked again and removed one new unused image.

**Comment by psonnera** [comment]
Merged images deletion but reverted https://github.com/openaps/AndroidAPSdocs/pull/2012/commits/f561a132cd6f51bed554ea329806b0887cc26456

**Pull request merged**
