### PR TITLE
Update Preferences.md

### PR DESCRIPTION
**Pull request by Vlin-der**
Aligned Advanced Settings and Wear Settings with AAPS v2.0

### CODE REVIEW

**Comment by Vlin-der** [comment]
Feel free to add any details to the text about Fabric Upload. I have typed a very basic explanation as I don't exactly know what is does...

**Comment by AdrianLxM** [comment]
Doesn't that remove too much?

**Comment by AdrianLxM** [comment]
Doesn't that remove too much?

**Comment by Vlin-der** [comment]
Good to ask that question Adrian. If I did my comparison correctly, the contents should be elsewhere in the wiki and none of the content will get lost. I will summarize below where to find the contents (sorry for the long read). Of course I am only human so I could be overlooking something. 

Thanks a lot to anyone who would be willing to go over it and give a shout if you are missing any of the contents!

.
> * OpenAPS MA

Nothing gets lost here.

.
> * Always use short average delta instead of... Enabling this setting is useful when you are using data from unfiltered sources such as xDrip+, as opposed to filtered sources such as an official Dexcom Receiver. Filtered data appears to be smooth, whereas unfiltered data can appear to be jumpy. This unfiltered data could cause AndroidAPS to apply Temporary Basal Rate changes more frequently than are really needed, as the OpenAPS algorithm reacts to the jumpy data. With this setting enabled, the OpenAPS algorithm will use the Short Average Delta (the average change in blood glucose over the past 15 minutes) instead of the last blood glucose reading received. This effectively has a "smoothing" effect on the data and attempts to compensate for any jumpy readings. Users of Abbot Freestyle Libre sensors collecting their glucose data via devices such as LimiTTers may find this setting provides better results with AAPS.
>For further tips regarding data smoothing when using xDrip+ as the data source, see [Smoothing Blood Glucose Data in xDrip+](../Usage/Smoothing-blood-glucose-data-in-xDrip.md).

This is covered on the page about Smoothing BG data: https://androidaps.readthedocs.io/en/latest/EN/Usage/Smoothing-Blood-Glucose-Data-in-xDrip.html
And in the Config Builder page the Average Delta setting is explained: https://androidaps.readthedocs.io/en/latest/EN/Usage/Open-APS-features.html?highlight=delta#advanced-settings

.
> * OpenAPS preferences.json - before changing any of these settings, please view the descriptions of the safety values used and why in the [OpenAPS docs](https://openaps.readthedocs.io/en/latest/docs/While%20You%20Wait%20For%20Gear/preferences-and-safety-settings.html).

Settings about Max Basal, Max IOB etc, incl link to the OpenAPS docs are covered (in even more detail than given here) on page about OpenAPS features: https://androidaps.readthedocs.io/en/latest/EN/Usage/Open-APS-features.html

.
> * 'Ignore profile switch events' will not send your current AndroidAPS profile to the pump. It is encouraged not to select this unless you are testing code, as for safety sending profile switch events to the pump's basal profile 1 means than should AndroidAPS stop working or loose connection with the pump then your pump will revert to the same profile as default rather than you having to manually enter it into the pump. For more information on profiles see [Profiles](/docs/Usage/Profiles).

As far as I know, this setting does not exist any more in AAPS v2.0
Issue#757

.
> * 'BT Watchdog' select this option if you keep loosing connection with your pump. When the pump looses connection it will toggle bluetooth off and on for you to improve the connection.

Covered on Config Builder page: https://androidaps.readthedocs.io/en/latest/EN/Configuration/Config-Builder.html#pump

.
>  Wear Settings
> * For more information on the wear watchface settings see [Watchfaces](../Configuration/Watchfaces.md).

No info lost here, is only a link.

**Comment by AdrianLxM** [comment]
you have multiple PRs on the same file. Could you please combine them that it is easier to see how things changed?
Thanks

**Comment by Vlin-der** [comment]
I  made the changes in #261 earlier and did not know how to continue with the same file. Watched a few youtube videos on how branches and forks and stuff work but could not figure out for the life of me how to put everything into 1 PR?!

If you could point me in the right direction on how to combine them, I would gratefully do so! ;)

**Comment by Vlin-der** [comment]
Messed up. New one: #298

**Pull request closed without merging**
