### PR TITLE
Split languages documentation projects

### PR DESCRIPTION
**Pull request by MilosKozak**

### CODE REVIEW

**Comment by MilosKozak** [comment]
https://androidaps.readthedocs.io/en/dev/

**Comment by MilosKozak** [comment]
languages are not visible @Andries-Smit

**Comment by Philoul** [comment]
Independent build for each language?

**Comment by Andries-Smit** [comment]
@MilosKozak Did you created a new project for each language? 
From the main project (English) you have to link the translations.
image

**Comment by Andries-Smit** [comment]
@Philoul Yes independent build, This way you can also have a GitHub action the flag issues in the project on a PR. So if someone change a page and opens a PR it is automatically validated before you merge

**Comment by MilosKozak** [comment]
image
Project is empty :(

**Comment by Andries-Smit** [comment]
Translations will show if you import a project for each translation
image

Each language project

Import import a project => Import Manually (Name androidaps-<language>)
Use the same using the same GitHub repository Repository URL
Set in the project Admin => Settings => Language the corresponding language
in Advanced settings => Default settings => Python configuration file set the relative URL to the correct conf.py for English docs/EN/conf.py and for the other languages docs/CROWDIN/<lang>/conf.py to match the file in the repo (replace with correct language code).

**Comment by MilosKozak** [comment]
image

**Comment by MilosKozak** [comment]
I added you to the project , try it
I only added DE for testing

**Comment by MilosKozak** [comment]
Build of DE is ok but I don't see menu to switch language.
Direct link works

**Comment by MilosKozak** [comment]
the language link always points to /latest/

**Comment by MilosKozak** [comment]
image

**Comment by MilosKozak** [comment]
except language and verison links it seems to work
great improvement

**Comment by Andries-Smit** [comment]
Though for each project you still have to select the right conf.py
`for the other languages docs/CROWDIN//conf.py to match the file in the repo (replace with correct language code).`
image

**Comment by MilosKozak** [comment]
i did

**Comment by Andries-Smit** [comment]
Are the other projects on the correct branche?

**Comment by MilosKozak** [comment]
hopefully i added it everywhere tha same way ... but builds are still running. let's check it later

**Comment by MilosKozak** [comment]
i added you. you should be able to see it

**Comment by Andries-Smit** [comment]
Ill check tomorrow

**Comment by Philoul** [comment]
Hello,
This morning, all languages works with direct link
 `https://androidaps.readthedocs.io/xx/dev/`
except hidden french language that still doesn't work...
https://androidaps.readthedocs.io/fr/dev/

**Comment by Andries-Smit** [comment]
@Philoul The last build on the dev branch of the French project failed, just retrigger the build on that branch for fix this

https://readthedocs.org/projects/androidaps-fr/builds/

**Comment by Philoul** [comment]
@Andries-Smit Great, now it works in all languages:👍

Before merge in master, I have 2 questions (only if it's not too complicated for both...) :
1) you proposed in your first PR to set some redirect links... I think it would be good to have at least a redirect link for the main page of each language...
Can you propose something in that way? 
@xJoe Do you think you can merge in master without this feature ? Only main page enough?
> Because we change the URL path for all languages we might break external link into the site. It would be good to setup some redirects to point to the right page. Due to the limitation the redirect supported in readthedocs, we have to investigate if we want to keep all, or only view re-directs

2) I saw, while testing in dev version, a little bug when we change language with menu, it always selects "latest" version and not "current selected" version ("dev")... I think it's better to keep selected version of doc when we switch languages if we want to compare translations (especially if we manage doc versions...). Is it easy to fix it?

**Comment by Andries-Smit** [comment]
1. There is no generic redirect we can setup for this solution. I have a script generating the redirects (for each page). I'll will run some more test over the weekend. I can add them to the repo, if you want. Ill run them against my dev doc site too, so you can review the effect. With the release, I can run the scripts after the split site goes live.

 2. It is correct behavior to that it point to latest. It will link you to the `default` version of the doc. We can not test that in the production doc site. As we don't want too swap all users. (For now testing the link; click the language, and that again on the branch `dev` and version)
 For now you can change the defaults. Though remind yourself to swap them back to latest and master after the go-live 
image

**Comment by xJoe** [comment]
Thanks for all the work and apologies for not participating much. My full time job is keeping me very busy at present and I did not have time do dive into all of this (which is more difficult as I am more the user type of guy - one of the reasons I am writing docs and not code ;-)).
Obviously the navigation on the left (looks nice) works different than before. I wanted to try to put the change language information on a separate page on top (above of Getting Started).
Another problem I have from user perspective is that I cannot change language if I am on a page other than start page.
I.e. https://androidaps.readthedocs.io/de/dev/Getting-Started/WhatisAndroidAPS/ -> no language change possible
If I start from https://androidaps.readthedocs.io/en/dev/ same page's URL is https://androidaps.readthedocs.io/en/dev/Getting-Started/WhatisAndroidAPS.html (.html instead of / at the end).

**Comment by Andries-Smit** [comment]
@xJoe The config for the German project was not equal to the English project. I corrected it for German project. (Don't have access to the other languages to fix this, can you?)

The builder type was not selected correctly https://www.sphinx-doc.org/en/master/usage/builders/index.html

This can be set in the Admin => Advanced Settings
image

**Comment by MilosKozak** [comment]
i've aded you to the rest of projects

**Comment by Andries-Smit** [comment]
@Philoul I opened a PR for the redirect scripts. #986 

For testing, the the script did run on my test site for French and German docs.
`https://androidapsdocs.readthedocs.io/en/latest/CROWDIN/fr/index.html` => 
`https://androidapsdocs.readthedocs.io/fr/latest/index.html` etc.

I can run the scripts after the split is moved into the production site.

**Comment by Philoul** [comment]
@Andries-Smit I tested on your test site and it works fine (not only for main page of each language page but also for all other pages... great!)
Thanks 👍👍👍

**Comment by xJoe** [comment]
Great work!

**Comment by xJoe** [comment]
Please let me know when you finished testing and want to move from dev to master.

Furthermore I'd be greatful if you could explain what we have to change in process concerning:
- Links in Github
- Build process in RTD
- Other things to consider

Thanks.

**Comment by Andries-Smit** [comment]
Hi @xJoe, I am not sure, if understand your questions completely.

1. Links are not changed from and to GitHub. The GitHub Repository is not split, only RTD projects are split and linked as translations. This way the search function only searches in one language at the time. The `Edit in GitHub` buttons will stay working as is. (you can test this here: https://androidaps.readthedocs.io/de/dev/ )
2. The build process is not changed, though if you always release manually. (Click button Build on a selective branch) You must do this for each project languages. To do so, all maintainers should be added to all project languages. However, I suggest moving to atomically building the docs based on the changes on the GitHub Repo with webhooks. When a commit is done in the repo it triggers automatically build the project and release doc site. See https://docs.readthedocs.io/page/webhooks.html a maintainer with both GitHub access and RTD project can enable them.
3. No other things to consider, just read the discussion on this and PR #969, and if you have some questions please let me know.

I finished test and development, you can release when you and the others feel confident.

Please let me know what date/time (timezone) you want to release, then I can assist if there are questions. (or run the redirect scripts)

**Comment by Philoul** [comment]
I made several tests on my side with fr and de (navigation from left menu or with internal links, switch languages, redirection of external link to old pages), and everything is Ok for me.

**Comment by AdrianLxM** [comment]
@Andries-Smit so you know if a good way to denounce the call of the webhook? Rtd would soon ban us again is we would build on each commit.

**Comment by Andries-Smit** [comment]
@AdrianLxM 'Again'? Did we get a ban before? That’s no fun!
It seems they limited a project with 2 builds parallel, to prevent overloading the system. (No need to ban us…)

When checking for some solitons, we cannot limit the GitHub webhooks to trigger only on some branches or throttled. I would like to see the throttling to be built in RTD. (Not sure if we could convince them to add it...) For now, we can leverage on the GitHub actions to only trigger a build on a push to the master branch only. (Assuming we do not commit to often om master). And let the action trigger the generic web hook. https://docs.readthedocs.io/en/stable/webhooks.html?#using-the-generic-api-integration

For an example implementation on the test environment, seems to do the job. see: https://github.com/Andries-Smit/AndroidAPSdocs/blob/automation/trigger-build/.github/workflows/trigger-rtd-build.yml

**Comment by xJoe** [comment]
I don't think a 

> 
> 
> i've aded you to the rest of projects

Could you please also add me? Thanks.

**Comment by xJoe** [comment]
Concerning automated build I understand that it is triggered when there is a commit in EN original (https://github.com/openaps/AndroidAPSdocs/tree/master/docs/EN).
I wouldn't do that because:
- Ban risk @AdrianLxM mentioned
- In the moment of commit in EN original there will be no translation to be updated.

At present I build Crowdin usually once a week and then RTD. Normally there is only change in 1 - 3 languages so manual build per language would be an option at least at the beginning.

**Comment by Andries-Smit** [comment]
In that case, when the language projects where created, the web hooks are automatically setup by RTD.
Can someone please switch `Pull requests` and `Pushes` them off, to prevent to many builds?
image

**Comment by xJoe** [comment]
> 
> 
> In that case, when the language projects where created, the web hooks are automatically setup by RTD.
> Can someone please switch `Pull requests` and `Pushes` them off, to prevent to many builds?

I guess this has to be done by @MilosKozak.

**Comment by xJoe** [comment]
I get this failure message when trying to build 10ln_master
grafik

**Comment by Andries-Smit** [comment]
@xJoe The `l10n_master` was building on each commit on all translated projects. I removed them from "Active" branches to prevent triggering them. Probably we have to the system rest for a while, and retry later today or tomorrow.

**Comment by AdrianLxM** [comment]
Who did set up the Webhooks again? @MilosKozak was that you?
It would be nice to have a quick alignment as they have no names in GitHub so I don't know what they belong to.
Some fail with 404 and 405s.

**Comment by AdrianLxM** [comment]
> 'Again'? Did we got a ban before? That’s no fun!

Yes, the way Crowdin pushed multiple commits we were flagged.
For the time being I simply switched all Webhooks related to rtd to `branch or tag creation` and `brach or tag deletion`.

We basically need a way to maually trigger all languages at once without being too much work.
We could apply a hack and use the project card as trigger. We could do a fake project with two columns and a single card. Whenever you want to trigger all builds, you can move the card.
Would that solve the problem?

**Comment by Andries-Smit** [comment]
@AdrianLxM Can you explain the "project card"? We could trigger a synchronized build by just adding a tag/release https://docs.github.com/en/github/administering-a-repository/about-releases

**Comment by AdrianLxM** [comment]
@Andries-Smit GitHub allows for Kanban styple Projects. This e.g. is one from the AndroidAPS repo:
image

In order to build all languages in the test or `dev` branch  to see if they build - before merging them to `latest`, we could simply move a card in the project. This way we wouldn't accumulate tags while debugging.

Full releases, I agree, would be nice to go with tags.

**Comment by Andries-Smit** [comment]
Yes. For larger stories connected to the project board seems a nice option. An more explicit build action could also be triggerd by an manual GitHub Action connected to the webhooks. Ill see if i can make a example. https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/

**Comment by Andries-Smit** [comment]
This seems to do the trick. 
- Create a Generic web hook in RTD for each project (language)
- Single GitHub Action with manual trigger https://github.com/Andries-Smit/AndroidAPSdocs/blob/automation/trigger-build/.github/workflows/trigger-rtd-build.yml
- When a build need to trigger; 
   - Got to GitHub Action tab
   - Click the `Run workflow` button
   - Select the branch.
- Wait for RTD to complete the all build and enjoy a cup of coffee!

image

**Comment by AdrianLxM** [comment]
That looks amazing @Andries-Smit. 👍  Maybe we find some time in the next couple of days to set that up together?

**Comment by Andries-Smit** [comment]
Sure! We can. I'll document it and prepare

**Comment by Andries-Smit** [comment]
The actions are in #992 
@AdrianLxM  Is there way I can send you in PM the tokens? Or alternative you can provide me temporary access to this repo, so I can add the secrets myself.

**Comment by AdrianLxM** [comment]
@Andries-Smit if you want to PM me, please use FB messenger (sent you a friend request) or write to adrian.m@inbox.com to join our slack or exchange threema, wire, signal contacts.

**Comment by xJoe** [comment]
@Andries-Smit and @AdrianLxM 
Something went wrong with German language. Clicking on the link as described in change language leads to folder \dev\ instead of \latest\. This might lead to 404 failure as not every page is in dev (i.e. https://androidaps.readthedocs.io/en/latest/changelanguage.html -> DE not available).
All other languages work fine as far as I have seen.
Could you please check and correct? Thanks.

**Pull request merged**
