### PR TITLE
Added en and de info about NS variables to coloring of careportal ages.

### PR DESCRIPTION
**Pull request by tanja3981**

### CODE REVIEW

**Comment by tanja3981** [comment]
The BAGE part that I documented here will be working only after PullRequest https://github.com/MilosKozak/AndroidAPS/pull/1681 was merged. 
The other variables are already implemented in the last releases.

**Comment by typ1-brods** [comment]
Nice! But please change only English files because German is auto built by the translation tool crowdin.

**Comment by tanja3981** [comment]
@typ1-brods reverted

**Comment by MilosKozak** [comment]
👍

**Comment by typ1-brods** [comment]
@AdrianLxM Go for it! ;-) Thank you, Tanja

**Comment by typ1-brods** [comment]
Merge to master, not to dev

**Pull request merged**
