### PR TITLE
Update temptarget.md

### PR DESCRIPTION
**Pull request by dottedfingertips**
Working through the broken links warnings.  This PR is my first effort on resolving them.  If succesful I'll work through the others.  Also updated objective numbers following 3.0 changes.

### CODE REVIEW

**Comment by xJoe** [comment]
I would not remove deep links to headlines as this is way easier to follow from my point of view.
So I'd use ../Usage/Objectives.html#objective-9-enabling-additional-oref1-features-for-daytime-use-such-as-super-micro-bolus-smb instead of just ../Usage/Objectives.rst.

**Comment by dottedfingertips** [comment]
I've updated that now to patch-1 on my branch so hopefully that is visible.  I wasn't sure if that would work so wanted to start with just getting rid of the 404 when you clicked on it as was.

Looking at the other warnings there are deep links pointing to pages that don't have anchor text in them so that may need to be done in stages.  Would you suggest trying to add anchors in to the destination first and then working backwards or start by restoring the working link and then going back to put the deep links back in place.

I realise I've been making some fairly random PRs for the last couple of days so I hope I'm not spamming you with unwanted changes!

**Comment by xJoe** [comment]
No spaming at all! ;-) On the weekend I have more time to look into PRs. On weekdays I have to ask for some patience.

Single PRs are easier to handle via Smartphone so I am not against those. If you do bigger changes first in your private repo please make a PR from time to time so that there will be no conflicts with doc changes from others. I had that with 3.0 changes and it took some time to solve this.

Sorry for my fault in syntax. For MD-files links to headlines must be w/o .html (https://androidaps.readthedocs.io/en/latest/make-a-PR.html#links). I corrected this myself.

I ment existing deep links. If at present there is no anchor you can leave it as it is or add one if you think this is helpful.

**Comment by xJoe** [comment]
Glad you are working on docs!

**Comment by dottedfingertips** [comment]
Thanks for resolving that issue and for the link to that page, it will be very useful.  I've been using the web UI to make the PRs so  far.  I might try to batch up the next lot in my branch and go from there.  I'm hoping to try and fix the link warnings next.   No worries if they go to you during the week and are left until next weekend before you get a chance to look at it.

It has been a very long time since I wrote code so I'm happy to assist with documentation where I can.

**Pull request merged**
