### PR TITLE
Watchface settings

### PR DESCRIPTION
**Pull request by Philoul**
I completed the "Watchface" page with the explanation of all parameters and all watchface list with names
The only parameter I did not understand is "Animations"
I do not know if it's specific to Circle Watchface ...

### CODE REVIEW

**Comment by xJoe** [comment]
You have to upload image to "AndroidAPSdocs/docs/EN/images/" (not docs/images!) in order to use it in wiki.

**Comment by Philoul** [comment]
Excuse me, I have forgotten to replace absolute link with relative link...

**Comment by xJoe** [comment]
Please upload the images to the folger ..\EN\images\ in your repository and make a PR to master.

**Comment by Philoul** [comment]
Images are in commits  https://github.com/openaps/AndroidAPSdocs/pull/673/commits/93fbdeb4c5a00e2d7dee6a58bb2d562bed461b6e and  https://github.com/openaps/AndroidAPSdocs/pull/673/commits/96c95c8b26b4006dd9a94d0f3b07e689f67782fd 
I tried to add them again in last commit but it's empty... Don't understand the problem (if you don't have them I'll send by mail...)

**Comment by xJoe** [comment]
Sorry. I did not see. Will merge after I solved the conflicts.

**Pull request merged**
