### PR TITLE
Update Insulin curve - Config-Builder.md

### PR DESCRIPTION
**Pull request by Vlin-der**
Changed text about Insulin curve:
1) Deleted text about bilinear curves, not used anymore in AAPS v2.0 (see PR #818)
2) Added link to other part of the wiki about minimum DIA of 5 hours
3) Correction where to find insulin curve graphs
4) Some minor rewordings

While translating, I noticed room for improvement for this part of the text. Removing bilinear curves was suggested earlier by comment from xJoe (German translator) on Crowdin.
My text is a proposal, suggestions / corrections are welcome.

### CODE REVIEW

**Comment by MilosKozak** [comment]
this link (https://androidaps.readthedocs.io/en/latest/EN/Getting-Started/Screenshots.html#insulin-profile) should be relative

**Comment by Vlin-der** [comment]
Changed hyperlink from: (https://androidaps.readthedocs.io/en/latest/EN/Getting-Started/Screenshots.html#insulin-profile)
into relative link: (../Getting-Started/Screenshots.md#insulin-profile)

Would the # be also the correct way to link to the 'Insulin Profile' chapter when using relative links?

**Comment by typ1-brods** [comment]
As far as I know, relative links to md files with anchors (#) have an issue. So you cannot relatively link to a special #, I think :-(

**Comment by Vlin-der** [comment]
Thanks for your answer, I removed the # part from the link. Please check if it works okay now.

**Pull request merged**
