### PR TITLE
migrate remaining rst files in md format - batch 1 of n

### PR DESCRIPTION
**Pull request by peterleimbach**
I want ot migrate the remaining rst files to md format. Their are only 40 files remaining with rst file extension and from my point of view it would make the work easier to have only one format for the documentation.

I used the pandoc utility on linux to migrate the files and changed the file extension from "*.rst" to "*.md".
$ find -name "*.rst" -exec pandoc -s -f rst -t gfm -i {} -o {}.md \;

I start here with batch 1 of n to look if the migration is done right and I can go forward with this.
I selected the Hardware folders in docs/EN as these file are small to overlook.

If the PR is accepted I can create the next PR für the next batch of 10 files or if you want all the rest as the migration is alreday done through the tool. It is more a question to check the PR of correctness.

### CODE REVIEW

**Comment by xJoe** [comment]
@peterleimbach Thanks. Did you adjust syntax (i.e. links) from rst format to md format?
And what is your plan for the links to the former .rst now .md pages as also here syntax matters (https://androidaps.readthedocs.io/en/latest/make-a-PR.html#links)?
One option could be to just merge your PR and then rework links based on link checker results (https://github.com/openaps/AndroidAPSdocs/actions/workflows/link-checker.yml).

**Comment by peterleimbach** [comment]
@xJoe
a) links inside Hardware folder have not changed and should be correct - 10 links to md files and 3 to rst files which we replaced by html during generation anyway.
b) links from outside will be okay as through generation the md files will be html files as before the rst files.
c) The translation of pumps.md and Smartwatch.md seems from my point of view NOT correct but I would let the generation run and check the output afterwards and correct it manually if necessary. It's a small issue which we can correct fast afterwards. Give me a sign when you have generated and I will check it asap.

**Comment by peterleimbach** [comment]
I checked the generated code again and there have been some errors which I corrected manually.

**Comment by xJoe** [comment]
@peterleimbach Please check if everything worked the way you planned. If so I could merge #1153 in master. Danke!

**Comment by peterleimbach** [comment]
Sorry you lost me. Please advice me how to move on.

I understand
1) @MilosKozak moved the PR to dev to get a clean code before pushing it into master which is fine for me.
2) @xJoe hints me to the link checker output from master which is not so good for me because it would be easier for me to get the link checker ouput from dev.
3) If I see further necessary changes on the files in the PR how do I proceed with this. How can I change them. At the moment I have from my point of view no write acess inside this PR.

Sorry for the confusion but I read in the documentation to make changes in master and not dev.

If you like to you can reject both of my PRs in master and I will start from scratch again with a PR against dev.
I would do this file by file to keep it easier for me and you to oversee until thinks are runing smoother.
You can then let the link checker run and accept after succesful run the PR.
I will move on until I corrected all link checker errors in dev -> EN.
You can then PR this from dev -> to master.

What do you think?

**Comment by xJoe** [comment]
Hi @peterleimbach,
as far as I understood:
1. PR was merged to master
2. You check dev for problems as you know which parts you changed (https://androidaps.readthedocs.io/en/dev/)
3. If changes are necessary do this in your repo. 
4. make new PR from your repo to master

For next steps 
1. Make PR from your repo to dev
2. I will merge and built RTD dev
3. Go on as described above

**Comment by peterleimbach** [comment]
Okay. I will check.

**Comment by peterleimbach** [comment]
@xJoe I corrected the link checker output via several small PRs as this was the safest way from my point of view.

Please let the link checker run and give me feedback.

I expect there should be no internal errors but two external links which I could not check at the moment will raise errors again.

Step by step...

**Comment by xJoe** [comment]
https://github.com/openaps/AndroidAPSdocs/actions/runs/1941575916

**Comment by peterleimbach** [comment]
@xJoe I corrected one more file. Please let the link checker run again and inform me when ready.

One error will remai which ist related to a read buffer size of the link checker environment which I can't handle.
I suggest you give this to one of the dev team.

**Pull request merged**
