### PR TITLE
adding explicit date instead of "at present" for the table

### PR DESCRIPTION
**Pull request by FlyingToto**

### CODE REVIEW

**Comment by FlyingToto** [comment]
also added the updates for the dash page.

**Review by vanelsberg — APPROVED** [review]

**Review by vanelsberg — APPROVED** [review]

**Comment by vanelsberg** [comment]
Thanks!

**Comment by peterleimbach** [comment]
@FlyingToto Thank you.

**Comment by peterleimbach** [comment]
@FlyingToto Thank you.

**Pull request merged**
