### PR TITLE
Add notes about LineageOS

### PR DESCRIPTION
**Pull request by pimeys**
I wanted to write a bit what it takes to install LineageOS to a phone for people who've never done it. Didn't want to go into details, just providing a list of things to do with links to the documentation.

### CODE REVIEW

**Comment by AdrianLxM** [comment]
Hello @pimeys thanks for helping.

The part about LineageOS should not go to the general phone page IMHO.
AndroidAPS indeed works with almost any Android phone from *5.1*. It is only one out of 4 pumps that does need a newer version.

I believe that part is better suited for the Combo pages - there already is some info about Lineage that could be replaced/augmented with your text.

**Comment by pimeys** [comment]
Ok, I'll take a look in couple of days. Need to pack and travel tomorrow.

**Comment by AdrianLxM** [comment]
@pimeys this PR atm has merge conflicts. Are you still working on it?

**Comment by pimeys** [comment]
Uh, sorry, I've been travelling around a bit and never had time to rethink this. Do we need this documentation or should we throw it away? I can do the rework if you think it's useful.

**Comment by AdrianLxM** [comment]
This has merge conflicts. Please open a new PR when these are resolved.

**Pull request closed without merging**
