### PR TITLE
Updates to screenshots page not currently showing in RTD

### PR DESCRIPTION
**Pull request by roppenheimer**

### CODE REVIEW

**Comment by AdrianLxM** [comment]
Doesn't that remove the other languages from the menu?

**Comment by roppenheimer** [comment]
I am only attempting to updated the English version of the documentation.

**Comment by roppenheimer** [comment]
OK, yes, I see the problem. Changes should only be to the EN part of the menu.

**Comment by roppenheimer** [comment]
I think I have merged the other language sections back in now.

**Comment by AdrianLxM** [comment]
The index is quite messed up. Would lead to wrong structure in non-english languages. Thanks @typ1-brods for the help.
Could you please clean this up and open a new PR.

closing (that it doesn't get merged by mistake)

**Pull request closed without merging**
