### PR TITLE
Change in image description

### PR DESCRIPTION
**Pull request by xJoe**
Small change to make new PR in order to have image of homescreen and status lights updated also in Crowdin translated versions.
Somehow l10n_master (https://androidaps.readthedocs.io/en/l10n_master/EN/Getting-Started/Screenshots.html) contains old image reference whereas actual wiki is up to date (https://androidaps.readthedocs.io/en/latest/EN/Getting-Started/Screenshots.html - English only, German shows no picture).

### CODE REVIEW

**Comment by Vlin-der** [comment]
@xJoe thanks for the update!

In the Insight-instructions are missing some of the screenshots, and some of the normal text is formatted like it is code (see screenshot) Can you please point me in the right direction how to make a PR for that, where can I find the source file for the translations? Thanks!

afbeelding

**Comment by xJoe** [comment]
Vlin-der sorry for the late answer.
I guess it is because of multiple spaces behind -. Try just one. Should also solve the image problem.
grafik
Please check in Crowdin. And also rename 2nd Combo pump in index.rst.
grafik

**Comment by Vlin-der** [comment]
Thanks for your suggestion. Removing the spaces does the job indeed!

Although I wonder if the real problem can be solved by changing only the Dutch file. The German one has the same, checked a few other languages and they had it too. I expect there must be another file which acts as the underlying source for all translations. I think we should be changing that one. 
Do you have any idea where I can find the underlying source file? Or any clue who knows how Crowdin and GitHub are connected at the back end?

Thanks again.

**Comment by xJoe** [comment]
@Vlin-der Thanks for the hint. I did not check the other languages.

@AdrianLxM could you please have a look into this? Or could you just try to send the English original to Crowdin once again? https://androidaps.readthedocs.io/en/latest/EN/Configuration/Accu-Chek-Insight-Pump.html looks good. Thanks for your help.

**Pull request merged**
