### PR TITLE
Split languages documentation projects

### PR DESCRIPTION
**Pull request by Andries-Smit**
This pull requires provides the configuration to split of the languages in different sub projects to make the doc site better accessible for search. 

Currently a search result show the results in all languages, making it hard to find the information the user is looking for, due to the many duplicates results from all the languages.

This will also makes the URL shorter
`https://androidaps.readthedocs.io/en/latest/CROWDIN/de/index.html`
to
`https://androidaps.readthedocs.io/de/latest/index.html`

The languages switcher is moved to the bottom menu, click on it to open 
image
Optional for the current users, we might need to add some info in the index to point the language menu, or to add a list of links to all languages available.

In the backend, we have to create a new documentation projects for each language. https://docs.readthedocs.io/en/stable/localization.html#project-with-multiple-translations

Each language project 
- Import `import a project => Import Manually`  (Name `androidaps-<language>`)
- Use the same  using the same GitHub repository `Repository URL`
- Set in the project  `Admin => Settings => Language` the corresponding language
- in `Advanced settings => Default settings => Python configuration file` set the relative URL to the correct `conf.py`  for English  `docs/EN/conf.py` and for the other languages `docs/CROWDIN/<lang>/conf.py` to match the file in the repo (replace <lang> with correct language code).

Then related the projects as translations from the English project
image

When the site are rebuild, clear you browser cash and refresh. 

Because we change the URL path for all languages we might break external link into the site. It would be good to setup some redirects to point to the right page. Due to the limitation the redirect supported in readthedocs, we have to investigate if we want to keep all, or only view re-directs https://docs.readthedocs.io/en/stable/user-defined-redirects.html

- [x] Hidden language French
- [x] Fix toctree
- [x] Remove test changes
- [x] Add hint to index for languages

Notes:
- To fix the menu toctree was missing the caption. This was enabled
- Test site is online a https://androidapsdocs.readthedocs.io/ (with 4 languages; English, German, French (hidden), Dutch.
- Added a _template as work around to add custom.css without upgrading the sphinx

### CODE REVIEW

**Comment by Philoul** [comment]
> The languages switcher is moved to the bottom menu, click on it to open
> Optional for the current users, we might need to add some info in the index to point the language menu, or to add a list of links to all languages available.

@Andries-Smit can we have "Hidden language" with your PR ? (important request)
=> is it possible to hide an available translated language in bottom menu ?

For example, currently French language is fully translated, available if you have a direct link, but not visible in main menu (it's hidden due to regulations)

**Comment by Andries-Smit** [comment]
We can hide a language. It is possible to hide the link to a language with CSS styling. This keeps the link in de html source but it does not show in the browser. Is that sufficient?

**Comment by Philoul** [comment]
Thanks for your answer, I think it's enough...

**Comment by MilosKozak** [comment]
can we handle this split in crowdin? I believe crowdin must push to one repo

**Comment by Andries-Smit** [comment]
@MilosKozak the code structure does not changes, 
The PR adds extra conf.py and the rest is administration work in readthedocs.io to add projects and link the translations

**Comment by Philoul** [comment]
> Test site is online a https://androidapsdocs.readthedocs.io/ (with 4 languages; English, German, French (hidden), Dutch.

I tried to access to hidden french page, but direct link https://androidapsdocs.readthedocs.io/fr/latest/  doesn't works (I can only access to the 3 "visible languages", with menu or with direct link)
Are you sure french language is included in test site online ?

**Comment by Philoul** [comment]
@Andries-Smit Now it works thanks
I love this proposal (french is hidden but when directly selected, I get the main menu in french on the left for navigation... great!)

**Comment by Andries-Smit** [comment]
@Philoul The wrong branch was selected in the administration settings, it should be working again

**Comment by Philoul** [comment]
But there are lots of dead links (I tested some of them in Screenshot page).
I suppose it will be necessary to update doc concerning links and anchor, and probably make some updates of these internal links in crowdin?

**Comment by Andries-Smit** [comment]
@Philoul the link of the test page where pointing to the original docs. To fix this, on the test site, I added an environment variable `SUB_DOMAIN` that can be set in the admin panel. This only needs to be configured in test config, and no variables have to be set in the production. Please empty browser cache and retest. After we split of the site we could take some actions to improve the technical quality, one language at the time. (Automation, build warnings, formatting, linters, link scans etc.)

**Comment by Philoul** [comment]
Thanks it works now, and I think it's a real great improvement...

To improve the maintainability of all links and if we want to be able to access them in AAPS, I think we need to change the way we create them in english to always have the same relative links in all languages (currently file names are identical but not anchors).

The best way is probably to first update these chapters of doc (internal link https://androidaps.readthedocs.io/en/latest/EN/make-a-PR.html#links and how to (not) translate link https://androidaps.readthedocs.io/en/latest/EN/translations.html#translate-headline-links) and probably define new rules for id/anchor names...

For next steps I can help (english and french doc currently) to update existing links in doc, but that should be discussed with @xJoe and @MilosKozak ...
I don't know how crowdin works to synchronize all languages with english... Do you think it's possible to update existing links with anchor in all languages if we want to transform them to untranslated stable links (and keep crowdin synchro) or is it necessary to first update in english (with new rules) and the use crowdin to update each language ?
Is it necessary to do all that work manually, or can we only update and check english doc and "migrate" links with crowdin (or any other tool) in all languages ?

**Comment by Andries-Smit** [comment]
@Philoul  Lets handle the two stories separately.  Let's first merge the language split. This will allow us to focus on technical quality.There after we can see if we can unify the anchors to support the in app help links. We can setup teams meeting so I can support on the migration.

**Comment by MilosKozak** [comment]
I merged to dev and run build
let's continue here https://github.com/openaps/AndroidAPSdocs/pull/982

**Pull request merged**
