### PR TITLE
WIP: Added ns.10be.de - Update Nightscout.md

### PR DESCRIPTION
**Pull request by xJoe**
Added ns.10be.de section from Deutsch (Specific) as of https://github.com/openaps/AndroidAPSdocs/issues/133

### CODE REVIEW

**Comment by xJoe** [comment]
Ok, then the version in Deutsch (Specific) was not correct (https://androidaps.readthedocs.io/en/latest/DE/konfiguration/konfigurations-generator.html#lokales-profil). I'll change the recommendation.
I'd like to change this but have been working on more parts of the Config Builder page in my repository and do not know how to send a PR just for the change of this part.
If it is okay for you I'd wait to send the pull request until I have finished the whole page.

**Comment by AdrianLxM** [comment]
Sure. Appreciate your work.
I added WIP (work in progress) to the title. Please remove it and drop me a note when you think it is in a state to be merged. Thanks.

**Comment by xJoe** [comment]
Adrian, can you explain ratio calculation in TDD screen? (see https://www.facebook.com/groups/AndroidAPSUsers/permalink/2261989330689138/) I'd like to add that information to the wiki. Thanks.

**Comment by xJoe** [comment]
I'm done now.

**Comment by AdrianLxM** [comment]
Thanks

**Pull request merged**
