### PR TITLE
Feat: Wear OS tiles Actions, TempT QuickWizard

### PR DESCRIPTION
**Pull request by Andries-Smit**
Wear OS tiles Actions, TempT QuickWizard are now available in the Dev branch. Not yet released.

### CODE REVIEW

**Comment by xJoe** [comment]
Thanks @Andries-Smit. But shouldn't we wait until it is released before publishing documentation?

**Comment by Andries-Smit** [comment]
Yes we could, or, we can add a note it will be available starting from the upcoming release.
You can tag the PR with "Next release"

**Comment by xJoe** [comment]
In the past the only window to new features were release notes and I'd prefer to keep it like that. But it is good to know there's already something prepared for docs.

**Comment by Andries-Smit** [comment]
@xJoe do you want it to be re-opened before the release?

**Comment by xJoe** [comment]
That was the plan.

**Pull request closed without merging**
