### PR TITLE
Update diabox link

### PR DESCRIPTION
**Pull request by KelvinKramp**

### CODE REVIEW

**Comment by psonnera** [comment]
@KelvinKramp Telegram is AFAIK the official channel for Diabox releases, latest is 2023_06_05 beta, are you sure driving users to Updowntown with version 2022.12.29_140 is sustainable? @LibreHack your input welcome.

**Comment by KelvinKramp** [comment]
maybe this is better?

https://github.com/openaps/AndroidAPSdocs/commit/f1fc618918fb02759d30501137012551eb68b076

**Comment by psonnera** [comment]
@KelvinKramp no, I talked with Anton and I think he dropped that due to local laws. Let me ask Diabox devs.

**Comment by KelvinKramp** [comment]
Ok thanks, the thing was that it was not easy to find the download option. Updating the link could save people couple minutes of time.

**Comment by psonnera** [comment]
I can add the link, but there is not guarantee Updowntown will be authorized to keep Diabox in the apps list. Linking to an old version is not the best idea. The official releases are in Telegram.

**Comment by KelvinKramp** [comment]
what about adding https://www.bubblan.org/setup/ so its more easier for users to find the info?

**Comment by psonnera** [comment]
What about this? https://www.bubblesmartreader.com/_files/ugd/6afd37_f183eabd4fbd44fcac4b1926a79b094f.pdf

**Comment by KelvinKramp** [comment]
Yes good! More informative than the current link.

**Comment by psonnera** [comment]
Sounds good, but please only PR in EN, not in a specific language.
Here only: https://github.com/openaps/AndroidAPSdocs/blob/master/docs/EN/Hardware/Libre2.md#3-use-diabox

**Comment by psonnera** [comment]
Merged in EN

**Pull request closed without merging**
