### PR TITLE
Fix WARNINGs Title underline too short

### PR DESCRIPTION
**Pull request by Andries-Smit**
Title underline should have a minimum length equal to the title.
https://docutils.sourceforge.io/docs/user/rst/quickstart.html#id20

Solves about 600 build warnings.

### CODE REVIEW

**Comment by MilosKozak** [comment]
i see you are touching translated files. Did you test we are able let Crowdin accept these changes? I believe Crowdin will overwrite it back

**Comment by Andries-Smit** [comment]
Let see, I hope so... I regex fixes so many files I no fun in the Crowdin UI :D If that is the case, we lose all the URL fixes of the other PR #991 
I assume so, as the 'edit in GH' button was on all pages, included the translated ones.

Ill, rebase these changes.

**Comment by xJoe** [comment]
So, shall we close this PR?

**Comment by Andries-Smit** [comment]
It would be better to understand at first the process of fixing translations issue in the both directions, GitHub => Crowdin
And how to deal with current conflicts. We had over 1000 broken links and mark up issues. 

Can we test the effect of the re-sync of translation with https://support.crowdin.com/github-integration/#uploading-translations-from-repo without breaking anything?

**Comment by MilosKozak** [comment]
Crowdin pulls changes from github repo. Translations are stored in Crowdin database. If source or translation is changed, Crowdin push to I10n_master branch. This branch is merged manually (but we can build RTD on this branch too to test it).
It's possible to export translations from Crowdin and upload back. I believe this is the way to go. There is Crowdin CLI too for automation.
Did you join crowdin? What username?

**Comment by Andries-Smit** [comment]
@MilosKozak I use my gihub account, so it will be: `Andries-Smit`

**Comment by MilosKozak** [comment]
I made you manager for now .... you can test it

**Comment by MilosKozak** [comment]
longer underline seems to do no problem. i'd try make EN version long enough (really long for all titles and translations).
then we can translate it once for every language and the rest can be done by pre-translations
opinion?

**Comment by Andries-Smit** [comment]
@MilosKozak indeed, In source languages EN, let's make them long enough for all languages as you suggest. If we make that the doc standard for all new heading, it will automatically propagate in all languages. Ill rebase the change and resolve the conflicts... so we can merge this as an alternative.

**Comment by Andries-Smit** [comment]
Conflicts resolved, ready to merge

**Comment by xJoe** [comment]
@Andries-Smit Did you my post in the other PR? (https://github.com/openaps/AndroidAPSdocs/pull/982#issuecomment-772274441)
DE is posting to dev instead of latest.

**Pull request merged**
