### PR TITLE
Drive G6 to external documents

### PR DESCRIPTION
**Pull request by psonnera**

### CODE REVIEW

**Comment by psonnera** [comment]
@navid200 please review the G6 page and feedback

**Comment by Navid200** [comment]
@psonnera 

Hi,

It seemed that you removed yourself from all xDrip-related development rooms.  However, it is possible that it was due to a virus or unintended change of permissions.  It was a surprise.
If there is anything we need to do to accommodate the restoration of your access, please let us know.

Please give me a few minutes as I go over this page and provide my suggestions.

**Comment by peterleimbach** [comment]
@psonnera thank you.

@LegoChemist 4yi

**Review by Navid200 — COMMENTED** [review]
Under General hints for looping with G6, it states that one should disable preemptive restart.
Preemptive restart is an xDrip setting.  But, since one does not have to use xDrip in order to use AAPS, perhaps, some clarification needs to be made here to clarify that preemptive restart is an xDrip setting.
Regardless, I would just like to clarify something here and let you decide how to deal with it.

More than a year ago, a change was made to xDrip so that preemptive restart would make no issues even if it was left enabled for Firefly.
As of that date, the only time the setting matters is if you are using a very old G6 that can use preemptive restart.
And if that is the case, I would strongly recommend to the user to enable preemptive restart.  I am going to explain that again and let you decide how to deal with it.

If you have a very old G6 and disable preemptive restart, you either will have to use G6 in non-native mode, which I strongly advise against because it disables factory calibration, or your sensor will stop after 10 days.  
  
Under "New transmitter with running sensor", almost at the end, I just have a comment.  
My concern with inserting a test strip between the sensor and transmitter while the transmitter is snapped into the sensor is what will happen to the petroleum jelly.
I have an article about petroleum jelly in the G6 sensor here: https://navid200.github.io/xDrip/docs/Petroleum-jelly-in-Dexcom-G6-Sensor.html

I admit that it is a very fast and easy method that allows a restart.
However, restarting a G6 will invalidate factory calibration.  Not everyone may be aware of this thinking that after a restart, everything will be as if starting a new sensor.  In reality, after a restart on day 10, readings will be significantly higher.  This needs to be clarified, which the link says nothing about in addition to my concern about Petroleum jelly.

**Pull request merged**
