### PR TITLE
Update Children.rst

### PR DESCRIPTION
**Pull request by timocm**
With the questions that are part of the future versions of AdroidAPS there is a bit of a confusion in the topic: monitoring children: how can you monitor AAPS of your child remotely? 
only NSClient can monitor AAPS; 
Xdrip+, Spike, Dexcom Follow are monitoring  BG's and giving  alarms but it would be wrong to regard them as remotely monitoring  AAPS.
So I have partially edited this page to introduce and explain NSClient app. 
I have also explained the other apps as tools to monitor BG and not AAPS ( since they do not monitor AAPS)
I have also include that Dexcom Follow can also be used from xDrip+ as well as from  the app Dexcom but with a note that there are other preferred options. 
Please consider the new headings:  methodology;  other tools and apps for partial monitoring 
Lastly the answers of the objective would need to be changed to only NSClient being correct, o rthe question rephrased to something like : "What tools are available to assist in the remote monitor of your child using AAPS?" and the answer would be all but "Loop app on iPhone ".

### CODE REVIEW

**Comment by xJoe** [comment]
Why would you say xDrip and Spike are not usable for monitoring AAPS? Both can display insulin given and carbs eaten for example.
As I do not use follow with NSClient which IOB / COB is shown? AAPS algorithm or NS algo?
Why would Dexcom Follow filled through xDrip allow "a larger number of followers from Dexcom follow"?

**Comment by timocm** [comment]
xDrip  uses a different algorithm than AAPS therefore different predictions.
Any removals of treatment done in AAPS does not reflect in xdrip.
xDrip does not have a IOB that is similar to AAPS as Xdrip does does not
track basal rates.
I have not used Spike but since Spike is also a collection app for CGM, I
believe that it would  have a similar function and similar limitations as
xDrip.


  Screenshot_20191010-034750_AndroidAPS.jpg
<https://drive.google.com/file/d/17kWp6qbdgRHUhazf2iyg8IJgqYbx5OGF/view?usp=drivesdk>

  Screenshot_20191010-034811_NSClient.jpg
<https://drive.google.com/file/d/17nRHxuFIVaoMa_zEAGgjTe2KDh2XdUvr/view?usp=drivesdk>

  Screenshot_20191010-034835_xDrip+.jpg
<https://drive.google.com/file/d/17mbit2hsOxE0vrkO1oRNaBVhpAjoDJcV/view?usp=drivesdk>

NSclient shows IOB / COB from AAPS. I do not have COB and IOB enabled in my
Nightscout app and the above screenshots are of AAPS on the master phone
and the NSclient and xdrip follower on a following phone.

Dexcom app has a limit of 5 people ( I think.... it has been some time that
I have used Dexcom) that can follow.  xDrip does not have a limiting number
(through Dexcom Follow). It is not Dexcom Follow app but the CGM collector
app that limits the number of people that can follow the BGLs.


The conclusion:
Remote monitoring of AAPS so that a follower can make an informed decision
to adjust TT, do profile switch, bolus remotely, etc should only be done
using NSClient app. Full spot. No other method should be encouraged,
suggested or recommended.
Just like xdrip, Spike and Dexcom use alarms to inform a person that BG's
are high or low and that a person needs to investigate why (going into AAPS
and make a decision what to do), likewise a person following should only
make a decision with all the formation from AAPS, ie NSclient app.

**Comment by timocm** [comment]
Screen shots from Google play description of Dexcom G5 app and from Dexcom
website explaining more about Dexcom Share2. Both  limit the number of
followers to 5.
  Google Play Store dexcom G5.jpg
<https://drive.google.com/file/d/17wY5D07x5l-bghHEBHgZseUPM9vjqQWa/view?usp=drivesdk>

  Dexcom Share limit.jpg
<https://drive.google.com/file/d/17vLe7eUd-lM_Xu4GFeZi7UenLW2aVdHl/view?usp=drivesdk>

**Comment by timocm** [comment]
A few screenshots of NSClient:
long press of basal; of IOB; of pump; of OAPS; of UPLD to show that all the
information of AAPS can be seen on NSClient

**Pull request closed without merging**
