### PR TITLE
NSClient download location, some fixes

### PR DESCRIPTION
**Pull request by szantos**
see issue #973

### CODE REVIEW

**Comment by szantos** [comment]
As this is my first contribution and PR any help or advice is appreciated :)

**Comment by xJoe** [comment]
Why did you remove 'Settings must be the same in AndroidAPS and NSClient.' from the top section? Don't you think this is a major information?

**Comment by szantos** [comment]
It was a dupe: it's written again below.

**Comment by xJoe** [comment]
Yes. But is a major information.

**Comment by szantos** [comment]
> Yes. But is a major information.

Ok, anyway thx for merging.

**Pull request merged**
