### PR TITLE
Update Omnipod DASH documentation

### PR DESCRIPTION
**Pull request by Freloner**
- Suspend function and  all Functions related to suspend deleted
- Engineering mode exclusive details deleted
- Other corrections suggested by @avereha

### CODE REVIEW

**Comment by Freloner** [comment]
@xJoe @avereha

**Comment by Freloner** [comment]
@xJoe @MilosKozak

**Comment by xJoe** [comment]
Sorry @Freloner Was on a business trip for a week.

**Comment by Freloner** [comment]
> Sorry @Freloner Was on a business trip for a week.

No worries i know

**Pull request merged**
