### PR TITLE
Updated status of omnipod

### PR DESCRIPTION
**Pull request by dexdan**

### CODE REVIEW

**Comment by typ1-brods** [comment]
I don't think linking winemug repo (omnipy) in this wiki is a good idea beacause it is not tested/stable enough. The hyperlinks to slack channels for Omnipod RileyinkAAPS development would be ok for me. What do you think, @AdrianLxM and @MilosKozak ?

**Comment by dexdan** [comment]
@typ1-brods Totally your call, and I 1 month ago I would have agreed with you. However, omnipy is now stable, and simple to install through use of a SD card image for the RaspberryPi. 

I understand it now has around 60+ users. I was (am) one of the original testers, having used the system since late February - things have come a long way since then and there is good stability / reliability of the system.

**Comment by typ1-brods** [comment]
I like it that your omnipy is working well. That's gread for people using omnipod. The furture possible pumps page in this wiki is for AAPS loop only. There is no link to Medtronic iOS Loop or Omnipod iOS Loop. And there should be no link to other AID APS like omnipy. People who want to loop that way can use google or ask in facebook groups for the link.

**Comment by dexdan** [comment]
Thanks, if rather disappointing.... omnipy _is_ for AAPS. It's certainly an 'other implementation', even if no link is provided. And there are other aspects of the page which are very out of date, eg "Loop (implementation is in the beginning stages; as far as I know, they managed to Init the pod and send the first TBR)". 

I'd be happy to do a pr of the page to update that and add non-linked Loop & omnipy refs if that helps?

**Comment by typ1-brods** [comment]
Yes, of course. You can make a new PR

**Comment by dexdan** [comment]
Thanks, new PR #370 created.

**Pull request closed without merging**
