### PR TITLE
Update to check whether patching was successful or not

### PR DESCRIPTION
**Pull request by alevar1975**
Successfullypatchedapp

### CODE REVIEW

**Comment by Philoul** [comment]
I can just tell you that my LibreLink is not patched and font is different...

Screenshot_20200504-180244

I planned to patch it but I haven't had time to do it yet ...

**Comment by alevar1975** [comment]
Bi there,In this case please add. In case you used Tino Kossmann’s LibreLink patcher:Then the changes I pulled forGesendet mit der GMX iPhone AppAm 04.05.20 um 18:06 schrieb Philoul
            
        
        
            
                Von: Philoul <notifications@github.com>Datum: 4. Mai 2020An: openaps/AndroidAPSdocs <AndroidAPSdocs@noreply.github.com>Cc: alevar1975 <alen.djonko@gmx.net>,Author <author@noreply.github.com>Betreff: Re: [openaps/AndroidAPSdocs] Update to check whether patching was successful or not (#830)
            
            
I can just tell you that my LibreLink is not patched and font is different...

I planned to patch it but I haven't had time to do it yet ...

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/openaps/AndroidAPSdocs/pull/830#issuecomment-623554794",
"url": "https://github.com/openaps/AndroidAPSdocs/pull/830#issuecomment-623554794",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by CaroGo** [comment]
Hi there, but that is exactly the point: the font in patched app looks different than in original version. So this is a good hint to verify that the patching has been successful. And this could be mentioned ...

**Comment by xJoe** [comment]
See https://github.com/openaps/AndroidAPSdocs/pull/834
Made new PR as images were not included. Please see https://androidaps.readthedocs.io/en/latest/EN/make-a-PR.html for further reference.

**Pull request closed without merging**
