### PR TITLE
Update to watches

### PR DESCRIPTION
**Pull request by davidkeddydb**
Would like to include language for interapp settings with Xdrip+ that some users have reported.

### CODE REVIEW

**Comment by xJoe** [comment]
I don't find the user reports. Can you please help me by posting a link?
Can you provide a screenshot where to put this info?
Thanks.

**Comment by davidkeddydb** [comment]
Evernote Camera Roll 20190816 100411

**Comment by AdrianLxM** [comment]
This doesn't seem watch related but CGM source related, so I'd add it to that page.
Good idea to add this! With the upcoming version it will become mandatory.

**Comment by davidkeddydb** [comment]
@AdrianLxM Ok, so you want me to look in CGM source and see if I can find a place to add it here within the AAPS docs?

**Comment by xJoe** [comment]
As this is a xdrip setting I moved the information to the xdrip settings page and made a link in bg source.
https://github.com/openaps/AndroidAPSdocs/pull/428

**Pull request closed without merging**
