### PR TITLE
Clean-up on SMB section

### PR DESCRIPTION
**Pull request by jbfeutz**
Some clean-up, additional explanation and changes. Incorporated the requests of Nik80 on the discord androidaps-wiki channel

### CODE REVIEW

**Review by peterleimbach — CHANGES_REQUESTED** [review]
Line 19) please replace "low carbs" with "slow carbs"
Line 29, okay
Line 45, okay
Line 59, okay
Line 65, okay
Line 82, I think that this is wrong. Are you sure
Line 85-87, the description is too long from my point of view. "If this option is enabled SMBs will not given when you set a temp target higher than your taret in the profile for that time. This feature is useful e.g. during sport where you want less IOB and don't want to get SMBs at all."
Line 96-101 I don't have this option in my version anymore 3.2.0-dev-i
Line 102 I don't have this option anymore
Line 111, okay
Line 118, okay
Line 123, okay
Line 126, okay
Line 130, okay
Line 132, okay
Line 134, okay
Line 136, okay
Line 138, okay

**Comment by jbfeutz** [comment]
@peterleimbach 

For line 82, how about: "Enable this to use SMB functionality. If disabled, no SMB will be given."
For 85 - 87: yeah this is the tricky one we have been discussing asking for a code change on. Your suggestion is actually the opposite of how it works. When the setting is disabled it has the functionality you described. Its hard to explain to someone how to use something briefly when it is backwards from what you would logically assume. I do feel that all of the information in my description is necessary to know how this feature will work. 
For 96 - 102: I'm pretty sure these are still in Master. I'm on autoISF branch, but I can build the most recent master to check if needed. 
Let me know your thoughts on above and I'll edit and submit

**Comment by peterleimbach** [comment]
@jbfeutz Okay. Please make the changes you suggest and submit them again. Thank you.

**Review by vanelsberg — APPROVED** [review]

**Comment by jbfeutz** [comment]
@peterleimbach is anything further needed from me on this one?

**Comment by peterleimbach** [comment]
@jbfeutz Thank you.

**Pull request merged**
