### PR TITLE
add cell padding, and embolden glossary terms

### PR DESCRIPTION
**Pull request by markvader**

### CODE REVIEW

**Comment by xJoe** [comment]
Are you sure this will work? In the past we had quite some problems with html in .md files.

**Comment by markvader** [comment]
Ah I see that sphinx doesn't come with support of markdown table. (i think the cell padding should work but probably not the <string>).
I don't know much about the backend of readthedocs but [this](https://github.com/ryanfox/sphinx-markdown-tables
) suggests that support can be added by running "pip install sphinx-markdown-tables" and adding 'sphinx_markdown_tables' into the extensions section of https://github.com/openaps/AndroidAPSdocs/blob/patch-2/docs/conf.py

**Comment by markvader** [comment]
alternatively I can remove all the `<strong>` html and just leave the cell padding

**Comment by xJoe** [comment]
To be honest I do not really know why glossary table works and it did not on other pages. And I never took the time to dive deeply into it as I am more the user type of guy.
What about this idea: I copy glossary as it is to a new page. If it looks like the actual page after building in RTD I will copy your changes to this "copy page", merge and build RTD. Than we can see if it works.

**Comment by markvader** [comment]
yes, we can try that

**Comment by xJoe** [comment]
Worked for the test page!

**Comment by xJoe** [comment]
And worked also for the original page. Thanks @markvader!

**Pull request merged**
